<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="shubhams-MacBook-Pro.local" ignored="0" name="Retry Multiple Fail Test Cases" tests="9" failures="2" timestamp="01 Oct 2020 09:18:37 GMT" time="0.032" errors="0">
  <testcase name="testA" time="0.005" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testA -->
  <testcase name="testA" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
at com.wa.qa.testcases.RetryTestClass.testA(RetryTestClass.java:11)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase name="testB" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.001" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <skipped/>
  </testcase> <!-- testB -->
  <testcase name="testB" time="0.0" classname="com.wa.qa.testcases.RetryTestClass">
    <failure type="java.lang.AssertionError" message="expected [a] but found [A]">
      <![CDATA[java.lang.AssertionError: expected [a] but found [A]
at com.wa.qa.testcases.RetryTestClass.testB(RetryTestClass.java:16)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase name="testC" time="0.0" classname="com.wa.qa.testcases.RetryTestClass"/>
</testsuite> <!-- Retry Multiple Fail Test Cases -->
